title: OSGi enRoute
author: OSGi Alliance
email: 
description: The Easy Way Towards Modularity


# language to use in html tag, can be overriden by page.lang
# lang: en 

sass:
    style: compressed

# You can look up the color names at http://materializecss.com/color.html
#colors:
#    primary_dark: black
#    primary_light: grey-darken-1
#    primary: grey-darken-3
#    accent: light-blue
#    primary_text: grey-darken-4
#    secondary_text: grey-darken-1
#    inverse_text: white
#    divider: grey-lighten-1
#    secondaryBackground: grey-lighten-4

hexcolors:
    primary_dark: '#0a385c'
    primary_light: '#37668a'
    primary: '#0b4470'
    accent: '#f18b21'
    primary_text: '#212121'
    secondary_text: '#757575'
    inverse_text: '#fff'
    divider: '#bdbdbd'
    secondaryBackground: '#f5f5f5'

# path to logo without leading slash e.g. images/logo.png or just the file name if it is in the root directory
logo: logo.png

# Github data, if present there will be a GitHub button in the navbar
github_button:
  user: osgi
  project:

# Twitter data, if present there will be a Twitter button in the navbar
twitter_button:
  user: OSGiAlliance

# any of these collections is used for nested pages
collections:
  landingpage:
    output: true
  tutorials:
    output: true